[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"
  VITE_API_URL="https://api-bva.herokuapp.com"
  VITE_APP_STRIPE_PUBLIC_KEY="pk_live_tdxzkzFxFZr4oa8QgFMCndI8"
  
[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"